# æˆ³ä¸€æˆ³çš„æ—¶é—´é—´éš”(å•ä½: åˆ†)
nudgeMin: 60
# æ–°äººå…¥ç¾¤æ¬¢è¿Žæç¤ºè¯­
# ä¸ºç©ºåˆ™ä¸æ¬¢è¿Ž
newMemberJoinMessage: 
  - æ¬¢æ·«
  - æ¬¢è¿Ž
# æ–°äººå…¥ç¾¤æ‘¸å¤´
newMemberJoinPat: true
# Bot è¢«æˆ³æ—¶çš„å›žå¤
# å¯ä»»æ„æŒ‰ç…§æ ¼å¼æ·»åŠ 
# å½“æˆ³ä¸€æˆ³æœªè§¦å‘åå‡»æ—¶ä¾¿éšæœºé€‰å–åˆ—è¡¨ä¸­çš„æ¶ˆæ¯å‘é€
# ä¸ºç©ºæ—¶ä¸å¼€å¯
nudgedReply: 
  - ãƒ¾(â‰§ã¸â‰¦)ã€ƒ
  - 'è¯·ä¸è¦æˆ³æˆ‘~>_<~'
  - åˆ«æˆ³å•¦
  - 'å†æˆ³æˆ‘ä½ å°±æ˜¯ç¬¨æ‰¹<( ï¿£^ï¿£)'
  - å¾èº«ä¹ƒé«˜æ€§èƒ½æœºå™¨äºº...å‘œå‘œ
  - ä½ æ˜¯æ˜¥æ˜¥çš„åˆç”Ÿ
  - æˆ‘æµ‹ä½ çš„ç 
# æˆ³ä¸€æˆ³è§¦å‘åå‡»çš„æ¦‚çŽ‡ç™¾åˆ†æ¯”(%)
counterNudge: 50
# æˆ³ä¸€æˆ³è§¦å‘åå‡»çš„å›žå¤æ¶ˆæ¯
counterNudgeMessage: 
  - æˆ³å›žåŽ»(ï¿£ â€˜i ï¿£;)
# æˆ³ä¸€æˆ³åå‡»ç»“æŸè¯­
counterNudgeCompleteMessage: 
  - å“¼
  - åˆ‡
# è§¦å‘æˆ³ä¸€æˆ³è¶…çº§åŠ å€çš„æ¦‚çŽ‡ (ä»…è§¦å‘åå‡»æ—¶)
superNudge: 15
superNudgeMessage: è¶…çº§åŠ å€ï¼
# è¶…çº§åŠ å€æˆ³ä¸€æˆ³æ¬¡æ•°
superNudgeTimes: 15
# Bot è¢«ç¦è¨€åŽå¯¹ç¦è¨€æ“ä½œè€…ç§èŠçš„æ¶ˆæ¯
# æ¶ˆæ¯ä¼šæŒ‰é¡ºåºæ”¾å‡º
botMutedMessage: 
  - å°±æ˜¯ä½ ç¦è¨€çš„æˆ‘å§
  - å’•å§†å§†ï¼Œæˆ‘è®°ä½ä½ äº†
# Bot è¢«ç®¡ç†å‘˜è§£ç¦æ—¶çš„å›žå¤
# å˜é‡: %ä¸»åŠ¨% (è§£ç¦æ“ä½œäºº)
botUnmuteMessage: æˆ‘è‡ªç”±å•¦ï¼æ„Ÿè°¢%ä¸»åŠ¨% å¤§äºº ðŸ¥µðŸ¥µðŸ¥µðŸ¥µðŸ¥µðŸ¥µðŸ¥µðŸ¥µ
# ç¾¤å‘˜è¢«ç¦è¨€æ—¶çš„å›žå¤
# å˜é‡: %ä¸»åŠ¨% (è§£ç¦æ“ä½œäºº), %è¢«åŠ¨% (è¢«è§£ç¦çš„æˆå‘˜)
# ç‰¹æ®Š: botOperatedMuteMessage ä¸º Bot ä¸»åŠ¨å‘èµ·ç¦è¨€æ—¶çš„å›žå¤
memberMutedMessage: %è¢«åŠ¨% è¢«%ä¸»åŠ¨% ç¦è¨€äº†ï¼Œå¥½å¯æƒœ
botOperatedMuteMessage: %è¢«åŠ¨% è¢«æœ¬å¤§äººç¦è¨€äº†ï¼Œå¥½å¥½åçœå§ï¼
# ç¾¤å‘˜è¢«è§£ç¦æ—¶çš„å›žå¤
# å˜é‡: %ä¸»åŠ¨% (è§£ç¦æ“ä½œäºº), %è¢«åŠ¨% (è¢«è§£ç¦çš„æˆå‘˜)
# ç‰¹æ®Š: botOperatedUnmuteMessage ä¸º Bot ä¸»åŠ¨è§£é™¤ç¦è¨€æ—¶çš„å›žå¤
memberUnmuteMessage: %è¢«åŠ¨% ä½ è‡ªç”±å•¦ï¼è¿˜ä¸å¿«æ„Ÿè°¢%ä¸»åŠ¨% å¤§äºº
botOperatedUnmuteMessage: %è¢«åŠ¨% ä½ è‡ªç”±å•¦ï¼è¿˜ä¸å¿«æ„Ÿè°¢æœ¬å¤§äºº
# å…¨ä½“è§£ç¦æ—¶çš„å›žå¤
# å˜é‡: %ä¸»åŠ¨% (è§£ç¦æ“ä½œäºº)
groupMuteAllRelease: å—¯ï¼Ÿå¥½åƒèƒ½è¯´è¯äº†è€¶
# æœ‰äººè¢«è¸¢å‡ºç¾¤æ—¶çš„å›žå¤
# å˜é‡: %ä¸»åŠ¨% (è¸¢äººæ“ä½œäºº), %è¢«åŠ¨% (è¢«è¸¢å‡ºçš„å‰ç¾¤å‘˜)
kickMessage: æœ‰ä¸ªäººè¢«%ä¸»åŠ¨% è¸¢äº†ï¼å¥½å¯æ€•
# æœ‰äººä¸»åŠ¨é€€ç¾¤æ—¶çš„å›žå¤
# å˜é‡: %ä¸»åŠ¨% (é€€å‡ºçš„å‰ç¾¤å‘˜)
quitMessage: æœ‰ä¸ªäººæ‚„æ‚„é€€ç¾¤äº†...
# åŠ å…¥å¤è¯»çš„å†·å´æ—¶é•¿ (å•ä½: ç§’)
# ä¸º-1æ—¶å…³é—­æ­¤åŠŸèƒ½
repeatSec: 25
# æ·«è¯­ç¿»è¯‘è§¦å‘å…³é”®è¯
yinglishCommand: ç¿»è¯‘
# æ·«ä¹±åº¦ (%)
yinLevel: 70
# éšæœºç¦è¨€çš„å‘½ä»¤
tenkiNiNokoSaReTaKo: å¤©å¼ƒä¹‹å­
# è½®ç›˜èµŒæ³¨å‘½ä»¤
roulette: èµŒ
# è½®ç›˜èµŒæ³¨å¼¹æ§½é‡
maxPlayer: 6
# è½®ç›˜èµŒæ³¨æ¶ˆæ¯
rouletteOutMessage: 
  - Bang!
roulettePassedMessage: 
  - ä½ æ‰£åŠ¨äº†æ‰³æœºï¼Œä½†ä»€ä¹ˆä¹Ÿæ²¡æœ‰å‘ç”Ÿ...
  - Bang! è¿œå¤„ä¼ æ¥äº†ä¸€å£°å·¨å“ï¼Œä½†ä½ ä»€ä¹ˆäº‹ä¹Ÿæ²¡æœ‰
# è½®ç›˜èµŒæ³¨æœ€å¤§ç¦è¨€æ—¶é—´ (å•ä½: ç§’)
rouletteOutMuteRange: 100
# è½®ç›˜èµŒæ³¨æ˜¯å¦å…è®¸é‡å¤åŠ å…¥
allowRejoinRoulette: false
# ç¥–å®‰é—®å€™å®¶äºº
maxZuanLevel: true
# ç¥–å®‰æ¬¡æ•°è¶…é™å›žå¤
outOfLimitation: æˆ‘æ‰ä¸ä¼šéª‚ä½ é‚£ä¹ˆå¤šæ¬¡å•¦ï¼
# æœºå™¨äººè¯´è¯å è¯è¯çš„æ¦‚çŽ‡
reduplicate: 40